import type { Metadata } from "next";
import { CartProvider } from "./context/CartContext";
import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Montserrat } from 'next/font/google';
import "./globals.css";
import CartPage from "./components/CartPopup";


const playfair = Playfair_Display({ 
  subsets: ['latin'], 
  variable: '--font-playfair' 
});

const montserrat = Montserrat({ 
  subsets: ['latin'], 
  variable: '--font-montserrat' 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${montserrat.variable} antialiased w-full`}
      >
        <CartProvider><CartPage/>{children}</CartProvider>
      </body>
    </html>
  );
}
